webproject/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name='webapp'
urlpatterns = [

path('',views.index,name="index"),
path('movie/<int:m_id>/',views.detail,name='detail'),
path('add/',views.add_movie,name='add_movie'),
path('update/<int:id>/',views.update,name='update'),
path('delete/<int:id>/',views.delete,name='delete')
]

webproject/webproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
path('',include('webapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webproject/webapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    imgs = models.ImageField(upload_to='gallery')
    year = models.IntegerField()

    def __str__(self):
        return self.name


from django.db import models

# Create your models here.

webproject/webapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','imgs','year']

webproject/webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)
def detail(request,m_id):
    movie=Movie.objects.get(id=m_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        imgs = request.FILES['imgs']
        year = request.POST.get('year')
        movie=Movie(name=name,desc=desc,imgs=imgs,year=year)
        movie.save()
    return render(request,"add.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

webproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<br><br><div class="one" style="position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);">
    <h1><u><font color="red">ADD MOVIES HERE</font></u></h1><br>
 <label><b>Enter movie name: <input type="text" name="name"></b></label><br><br>
  <label><b>Enter movie year: <input type="number" name="year"></b></label><br><br>
   <label><b> Enter movie description:<input type="textarea()" name="desc" rows="4" cols="5"></b></label><br><br>
    <label><b>Add an Image :  <input type="file" name="imgs"></b></label><br><br><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit"></div>
</form>
{% endblock %}}

webproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="static/style.css">

</head>
<body bgcolor="green">
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

webproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
  {% csrf_token %}
  <h6> ARE YOU SURE TO DELETE THIS MOVIE ? </h6>
  <input type="submit"></form>
  {% endblock %}

webproject/templates/details.html
{% extends 'base.html' %}
{% block body %}

  <div class="container">
        <div class="row">
            <div class="col-md-6"><br><br>
                <img src="{{movie.imgs.url}}" width="500" height="500">
            </div>
  <div class="col-md-6"><br><br>
      <h4><u><b>{{movie.name}}-{{movie.year}}</b></u></h4><br>
         {{movie.desc}}<br><br>
      <a class ="btn btn-primary" href="{% url 'webapp:update' movie.id %}">UPDATE</a>
      <a class ="btn btn-danger" href="{% url 'webapp:delete' movie.id %}">DELETE</a>
{% endblock %}
  </div>
        </div>
  </div>

webproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="one" style="position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);">
<form method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
  </form>
{% endblock %}

webproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

  <div class="container">
      <div class="row">
       {% for i in movie_list %}
        <div class="col-md-3"><br><br>
            <div class="card">
                <img class="card-img-top" src="{{i.imgs.url}}" alt="" width="200" height="250">
                    <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                        <h5 class="card-title">{{i.year}}</h5>
                    <a href="{% url 'webapp:detail' i.id %}" class="btn btn-primary">View Details...</a>
                    </div>
             </div>
        </div>{% endfor %}
      </div>
      <br>
      <br>
       <a href="{% url 'webapp:add_movie'  %}" class="btn btn-success">ADD MORE MOVIES HERE </a>
  </div>
{% endblock %}


<!--<img src="{{i.imgs.url}}" width="100" height="100"><br>
    <a href="{% url 'webapp:detail' i.id %}">{{i.name}}</a>-->
